version: '3'
services:
  database:
    image: mongo:latest
    container_name: 'my-mongodb-container'
    environment:
      - MONGO_IP=localhost
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017-27019:27017-27019'
